### ISSUE TITLE
Make it official?

### ISSUE THREAD

**Issue by atomiks** [lozinsky/vue-floating-ui#10]
Thank you for creating this ❤️ 🎈 

Are you interested in placing this under `@floating-ui/vue`?

**Comment by lozinsky** [comment]
Thank you ❤️

`vue-floating-ui` provides low-level bindings like `@floating-ui/react-dom`. It supports `vue@^2` and `vue@^3` via [`vue-demi`](https://github.com/vueuse/vue-demi). I'd like to keep this compatibility as long as the `vue@^2` is still supported.

> Vue 2 will reach End of Life by the end of 2023 ([source](https://blog.vuejs.org/posts/vue-2-7-naruto.html))

It really can be placed under `@floating-ui/vue` as it is. (I can do the PR?)

**Comment by atomiks** [comment]
> I can do the PR?

That would be great. I imagine the two packages folders you have can both live in [`packages/vue`](https://github.com/floating-ui/floating-ui/tree/master/packages).

**Comment by lozinsky** [comment]
:tada: https://github.com/floating-ui/floating-ui/pull/2034
